CREATE USER data WITH PASSWORD 'data';

CREATE DATABASE data;

GRANT ALL PRIVILEGES ON DATABASE "data" to data;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "data";

ALTER USER data WITH SUPERUSER;
